### PR TITLE
Rename pallmall test app to H2MS

### PR DESCRIPTION
**Pull request by stbenjam**
I'd like to get in the habit of doing code reviews, so opening a pull request for this.  This PR renames the application from pallmall to H2MS.

### CODE REVIEW

**Comment by stbenjam** [comment]
Closed/reopened to trigger Travis. You can see it ran by expanding "Show all checks", and see the output of the tests by clicking through to travis-ci.org.

**Comment by shinwachi** [comment]
Looks good. Are we to branch all the time?

**Comment by shinwachi** [comment]
Ok, Apparently I have no idea what I'm doing.

**Comment by shinwachi** [comment]
Redoing comment.

**Comment by stbenjam** [comment]
Review the PR using the review function (you have to switch to the Files changed tab) and you can add your approval there.

Typically the GitHub workflow is  (1) fork the repo to your own github account (once) (2) create a feature branch (3) commit whatever changes (4) open a pull request in GitHub, and (5) it gets reviewed, (6) once reviewed and approved it can be merged. 

We didn't really talk in detail about how we'll do code changes, but there's a poll in Slack from the other day if we want to do an approach like that.

If anyone's not super familiar with git I found https://try.github.io/ really helpful.

**Pull request merged**
