### PR TITLE
Add roles to user registration

### PR DESCRIPTION
**Pull request by K-Tros**
### Please give a short summary of what's included in this submission
This PR adds role selection checkboxes to the user page for logged-in users. This functionality assumes that only certain authenticated users will be allowed to access the users page, so role edits are locked down to only those users with appropriate access.

Relies on https://github.com/2018swecapstone/h2ms/pull/97.

### Checklist
- [X] The Pull Request title describes the changes I've made
- [X] I've reviewed the **Files changed** tab
- [X] The code in the **Files changed** tab meets our style guides
- [X] New classes and public methods in the **Files changed** tab are documented
- [X] I've added two reviewers for this pull request

##### I've reviewed the observe page, reports page, and any page directly affected by these changes
- [ ] For Mobile (width: ~320px) [View](http://whatismyscreenresolution.net/multi-screen-test?site-url=http://localhost:4200/login&w=320&h=480)
- [ ] For Tablet landscape (width: ~1024px) [View](http://whatismyscreenresolution.net/multi-screen-test?site-url=http://localhost:4200/login&w=1024&h=768)
- [ ] For Desktop (width: 1920px) [View](http://whatismyscreenresolution.net/multi-screen-test?site-url=http://localhost:4200/login&w=1920&h=1080)
- [ ] I've reviewed the **Files Changed** Tab and left constructive criticism (if applicable)

###### Optional
- [ ] For Tablet portrait (width: ~768px) [View](http://whatismyscreenresolution.net/multi-screen-test?site-url=http://localhost:4200/login&w=768&h=1024)

### CODE REVIEW

**Comment by WesleySkillern** [comment]
If I select any user, "Add a new person", the form retains the first user's information, but it should probably be cleared in between selections.

**Comment by WesleySkillern** [comment]
If I submit a new user, we should probably refresh the User drop list, so that they can see that the user was successfully added. It doesn't show until I refresh the page.

**Comment by WesleySkillern** [comment]
Minor inconsistency with naming: The tab in the hamburger icon menu is called User, but the page is titled People.

**Comment by K-Tros** [comment]
@WesleySkillern @benjenkinsv95 PR has been updated to address the comments.

**Comment by WesleySkillern** [comment]
I get a 401 when trying to hit "Sign Up" from login screen?

**Comment by WesleySkillern** [comment]
Could we have a header for the Roles section? E.g.
____________________________________
Roles
O Admin O Observer O User

**Comment by WesleySkillern** [comment]
If I edit an existing User's name, click save, and refresh the page, the User is gone from the mat-select list.

**Comment by WesleySkillern** [comment]
If I create a new User and click Save, the recently created User does not appear in the mat-select.

**Comment by WesleySkillern** [comment]
If I select "Add a new user", the mat-select shows "Select a user to edit or add". Not sure if there is a cleaner way. Just a little odd. Nonessential fix.

**Comment by WesleySkillern** [comment]
How do I delete a User?

**Comment by WesleySkillern** [comment]
Some minor nit-pick items that are non essential to merge: 
- "Save" button should be disabled until changes are made to selected User.
- After clicking "Save", mat-select refreshes (makes sense), but user form data is still in form. Clear it? Or better yet reselect the Edited/Saved User?

More important for merge:
- 401 after Save new user from Login

screen shot 2018-05-01 at 12 58 59 am

**Comment by WesleySkillern** [comment]
Almost there!

**Comment by K-Tros** [comment]
@WesleySkillern Fixed the latest round of issues. There is one remaining issue that I know about that there is no good way around. After submitting and clearing the form, the required fields are marked as red. The only supported way that I was able to find to clear the redness was to recreate the entire form, which refreshes the whole page. I think the redness is acceptable to avoid a full refresh.

**Pull request merged**
